// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using River_Pollution_Survey.Models.DBModels;

#nullable disable

namespace River_Pollution_Survey.Migrations
{
    [DbContext(typeof(RiverDBContext))]
    partial class RiverDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("River_Pollution_Survey.Models.DBModels.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("River_Pollution_Survey.Models.DBModels.Site", b =>
                {
                    b.Property<Guid>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WasteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SiteId");

                    b.HasIndex("WasteId");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("River_Pollution_Survey.Models.DBModels.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Contact")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SiteId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("River_Pollution_Survey.Models.DBModels.Waste", b =>
                {
                    b.Property<Guid>("WasteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("WasteType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WasteId");

                    b.ToTable("Wastes");
                });

            modelBuilder.Entity("River_Pollution_Survey.Models.DBModels.Site", b =>
                {
                    b.HasOne("River_Pollution_Survey.Models.DBModels.Waste", "Waste")
                        .WithMany()
                        .HasForeignKey("WasteId");

                    b.Navigation("Waste");
                });

            modelBuilder.Entity("River_Pollution_Survey.Models.DBModels.User", b =>
                {
                    b.HasOne("River_Pollution_Survey.Models.DBModels.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("River_Pollution_Survey.Models.DBModels.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId");

                    b.Navigation("Role");

                    b.Navigation("Site");
                });
#pragma warning restore 612, 618
        }
    }
}
